In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [3]:
np.inner(a,b)

32

In [4]:
c=np.matrix([[1,2,3],[2,4,6]])
type(c)

numpy.matrix

In [5]:
np.transpose(c)

matrix([[1, 2],
        [2, 4],
        [3, 6]])

In [13]:
m=np.array([[1,2,3],[3,5,4],[9,8,7]])
det=np.linalg.det(m)
det

-30.000000000000014

In [14]:
np.linalg.inv(m)

array([[-0.1       , -0.33333333,  0.23333333],
       [-0.5       ,  0.66666667, -0.16666667],
       [ 0.7       , -0.33333333,  0.03333333]])

In [16]:
w,v=np.linalg.eig(m)

In [17]:
w

array([14.1240384, -2.1240384,  1.       ])

In [18]:
v

array([[-0.26386292, -0.62669709,  0.34684399],
       [-0.45873861, -0.16385061, -0.78039897],
       [-0.84848998,  0.76184233,  0.52026598]])