In [2]:
import numpy as np

In [3]:
x=np.array(([2,9],[1,5],[3,6]),dtype=float)
y=np.array(([92],[86],[89]),dtype=float)
x=x/np.amax(x,axis=0)
y=y/100

In [4]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [12]:
def derived_sigmoid(x):
    return x*(1-x)

In [6]:
epoch=5
lr=0.1

In [7]:
input_layer=2
hidden_layer=3
output_layer=1

In [8]:
wh=np.random.uniform(size=(input_layer,hidden_layer))
bh=np.random.uniform(size=(1,hidden_layer))
wout=np.random.uniform(size=(hidden_layer,output_layer))
bout=np.random.uniform(size=(1,output_layer))

In [13]:
for i in range(epoch):
    #forward prop
    hinp1=np.dot(x,wh)
    hinp=hinp1+bh
    h_act=sigmoid(hinp)
    outinp1=np.dot(h_act,h_act)
    outinp=outinp1+bout
    output=sigmoid(outinp)
    
    
    eo=y-output
    outgrad=derived_sigmoid(output)
    d_output=eo*outgrad
    eh=d_output.dot(wout.T)
    hiddengrad=derivatives_sigmoid(h_act)
    d_hidden=eh*hiddengrad
    wout+=h_act.T.dot(d_output)*lr
    wh+=x.T.dot(d_hiddenlayer)*lr
    print("---------------------epoch-",i+1,"starts--------------------")
    print("input",str(x))
    print("actual out",str(y))
    print("predicted",output)
    print("----------------------epoch_end------------------------------")

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [16]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)
X = X / np.amax(X, axis=0)  # maximum of X array longitudinally
y = y / 100


# Sigmoid Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


# Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)


# Variable initialization
epoch = 7000  # Setting training iterations
lr = 0.1  # Setting learning rate
inputlayer_neurons = 2  # number of features in data set
hiddenlayer_neurons = 3  # number of hidden layers neurons
output_neurons = 1  # number of neurons at output layer
# weight and bias initialization
wh = np.random.uniform(size=(inputlayer_neurons, hiddenlayer_neurons))
bh = np.random.uniform(size=(1, hiddenlayer_neurons))
wout = np.random.uniform(size=(hiddenlayer_neurons, output_neurons))
bout = np.random.uniform(size=(1, output_neurons))
# draws a random range of numbers uniformly of dim x*y
for i in range(epoch):
    # Forward Propogation
    hinp1 = np.dot(X, wh)
    hinp = hinp1 + bh
    hlayer_act = sigmoid(hinp)
    outinp1 = np.dot(hlayer_act, wout)
    outinp = outinp1 + bout
    output = sigmoid(outinp)
    # Backpropagation
    EO = y - output
    outgrad = derivatives_sigmoid(output)
    d_output = EO * outgrad
    EH = d_output.dot(wout.T)
    hiddengrad = derivatives_sigmoid(hlayer_act)
    d_hiddenlayer = EH * hiddengrad
    wout += hlayer_act.T.dot(d_output) * lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) * lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    print("----------------------------epoch-",i+1,"starts------------------------")
    print("Input: \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n", output)
    print("----------------------------epoch-",i+1,"ends------------------------")
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n", output)


----------------------------epoch- 1 starts------------------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.88950503]
 [0.87627078]
 [0.89156381]]
----------------------------epoch- 1 ends------------------------
----------------------------epoch- 2 starts------------------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.88953909]
 [0.87630558]
 [0.89159737]]
----------------------------epoch- 2 ends------------------------
----------------------------epoch- 3 starts------------------------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.88957285]
 [0.87634006]
 [0.89163062]]
----------------------------epoch- 3 ends------------------------
----------------------------epoch-